= nRF51-ble-broadcast-mesh

Bluetooth Low Energy based Rebroadcasting mesh implementation on the nRF51.
Works with softdevices S110 v7.x and S130 with Timeslot API.
Offers an API for implementing your own mesh enabled application, operating
concurrently with regular BLE applications.

== Basic concepts

This framework provides a connection-less, rebroadcasting infrastructure for
synchronizing states across a set of BLE enabled nodes. All nodes receive all
messages that are transmitted within their range, and any node may update the
mesh-global states. There is no hierarchy, and no directed data links. 

The framework resides on top of the nRF51 Softdevice, utilizing the Timeslot
API to allocate radio time. All nodes in the mesh share a set of dataslots,
address by handles. These handle-value pairs are propagated through the mesh
with version numbers, with the objective of synchronizing the same values
across all nodes in the mesh. Each time a node overwrites a value, it
increments the version number, and all nodes that receive a broadcast message
with a version number that is higher than the one in its database, will adapt
this new version of the value. 

The value propagation is controlled by an implementation of the IETF RFC6206
"Trickle", a flood control algorithm for lossy, low power networks. The Trickle
algorithm dynamically decides intervals at which a value will be broadcasted by
a node, based on how many consistent messages the node picks up, and when the last
update to the state it manages was. The Trickle algorithm dynamically adapts to
node density and value update frequency.

The framework provides each handle-value pair with one Trickle-instance (an
isolated version of the algorithm), and utilizes the Softdevice GATT server
structure to store the values. All values are stored as characteristics within
one "Mesh"-GATT Service, which is accessible to external nodes through a
classic BLE Softdevice connection, implemented in application space. The "BLE
Gateway example" displays a way to achieve such behavior.

== Structure
The project is split into two parts: _rbc_mesh/_ (the framework), and a folder with
examples. The framework is interfaced through a set of API functions,
exclusively contained in the _rbc_mesh.h_ file. 


=== Framework Modules
The framework is split into several separate modules, each of which is
responsible for managing various aspects of the framework.

* *rbc_mesh* The top module of the framework, contains all API functions and is
the only module that should be accessed by the application.

* *mesh_srv* The value storage module, communicates with the Softdevice's GATT
server, and maps all handles to GATT characteristics.

* *timeslot_handler* A module communicating with and abstracting the nRF51
Softdevice Timeslot API and manages the two interrupt contexts the framework
runs in.

* *trickle* Implementation of the IETF RFC6206 "Trickle" algorithm for
mesh-global state propagation.

* *ll_control* Lower level packet handler. Abstracts the radio interface and
packet format for the mesh_srv-module. 

* *radio_control* Asynchronous radio abstraction. Offers a way for higher level
modules to queue radio events and packets, and also provides callbacks on
various radio events.

* *timer_control* Interfaces the NRF_TIMER0 hardware module by managing timer
capture allocations and callbacks. Tightly integrated with the radio module.

=== API

The API is exclusively contained in the _rbc_mesh.h_ file in _rbc_mesh/_, and
while the other framework files need to be included in the build process or
Keil project, they should not be interfaced directly. 

==== The API provides the following functions to the user:

*Initialize framework*
[source,c]
----
uint32_t rbc_mesh_init(uint32_t access_addr, 
        uint8_t channel, 
        uint8_t handle_count, 
        uint8_t adv_int_ms); 
----
This function must be called before any other framework function, and sets up
the Mesh GATT service and enables listening for incoming mesh messages.

All nodes within the same mesh network must be set up with the same access
address and channel, but handle_count and adv_int_ms may be different. 

'''

*Request external value update*
[source,c]
----
uint32_t rbc_mesh_value_req(uint8_t handle);
----
Request a state update from other nodes on the same mesh network on the given
value-handle pair. Forces the node to broadcast an empty version 0-message to
other nodes, which, in turn will answer with their version of the
handle-value-pair. This way, new nodes may get up to date with the rest of the
nodes in the mesh.

'''

*Update value*
[source,c]
----
uint32_t rbc_mesh_value_set(uint8_t handle, uint8_t* data, uint16_t len);
----
Update the value represented by the given handle. This will bump the version
number on the handle-value pair, and broadcast this new version to the rest of
the nodes in the mesh. 

The `data` array may at most be 27 bytes long, and an error will be returned if
the len parameter exceeds this limitation.

'''

*Get value*
[source,c]
----
uint32_t rbc_mesh_value_get(uint8_t handle, uint8_t* data, uint16_t* len);
----
Returns the most recent value paired with this handle. The `data` buffer must
be at least 27 bytes long in order to ensure memory safe behavior. The actual
length of the data is returned in the `length` parameter.

'''

*Get operational access address*
[source,c]
----
uint32_t rbc_mesh_access_address_get(uint32_t* access_address);
----
Returns the access address specified in the initialization function in the
`access_address` parameter.

'''

*Get operational channel*
[source,c]
----
uint32_t rbc_mesh_channel_get(uint8_t* channel);
----
Returns the channel specified in the initialization function in the
`channel` parameter.

'''

*Get handle count*
[source,c]
----
uint32_t rbc_mesh_handle_count_get(uint8_t* handle_count);
----
Returns the handle count specified in the initialization function in the
`handle_count` parameter. 

'''

*Get minimum advertisement interval*
[source,c]
----
uint32_t rbc_mesh_adv_int_get(uint32_t* adv_int_ms);
----
Returns the minimum advertisement interval specified in the initialization
function in the `adv_int_ms` parameter. 

'''

*BLE event handler*
[source,c]
----
uint32_t rbc_mesh_ble_evt_handler(ble_evt_t* evt);
----
Softdevice BLE event handler. Must be called by the application if the
softdevice function `sd_ble_evt_get()` returns a new event. This will update
version numbers and transmit data if any of the value-characteristics in the
mesh service has been written to through an external softdevice connection. May
be omitted if the application never uses any external connections through the
softdevice.

'''

*Softdevice event handler*
[source,c]
----
uint32_t rbc_mesh_sd_irq_handler(void);
----
Handles and consumes any pure softdevice events (excluding softdevice BLE
        events. See the official
        https://devzone.nordicsemi.com/docs/[Softdevice documentation] for
        details). Should be called on each call to `SD_IRQHandler()`.

==== Return values
All API functions return a 32bit status code, as defined by the nRF51 SDK. All 
functions will return `NRF_SUCCESS` upon successful completion, and all
functions except the `rbc_mesh_init()` function return
`NRF_ERROR_INVALID_STATE` if the framework has not been initialized. All
possible return codes for the individual API functions (and their meaning)
are defined in the `rbc_mesh.h` file. 

==== Framework events
In addition to the provided API functions, the framework provides an event
queue for the application. These events are generated in the framework and
should be handled by the application in an implementation of the
`rbc_mesh_event_handler()` function defined in _rbc_mesh.h_. The events come in
the shape of `rbc_mesh_event_t*` structs, with an event type, a handle number,
    a data array and an originator address.

The framework may produce the following events:

* *Update*: The value addressed by the given handle has been updated from an
external node with the given address, and now contains the data array
provided in the event-structure.

* *Conflicting*: A value with the same version number, but different data or
originator has arrived at the node, and this new, conflicting value is provided
within the event-structure. The value is *not* overwritten in the database, but
the application is free to do this with a call to `rbc_mesh_value_set()`.

* *New*: The node has received an update to the indicated handle-value pair,
which was not previously active.

=== Examples

The project contains two simple examples and one template project. The two
examples are designed to operate together, and show off an extremely simple
example scenario where two handle-value pairs decides the state of the two LEDs
on the nRF51 evkit (or red and green LED on the nRF51 dongle). The examples
have been tested with boards PCA10000, PCA10001 and PCA10003.

The template provides a basis for implementing your own applications with the
framework, and addresses the different eventhandlers and initialization
functions, without any additional functionality.

==== LED Mesh example
This example reads the buttons on the nRF51 evkit boards, and sets the LEDs
accordingly. It also broadcasts the state of the LEDs to the other nodes in the
same mesh, which will copy the state of the node that registered a button push.
This example can also be flashed to the nRF51 dongles (PCA10000), even though
these boards don't have any buttons. The dongle-nodes will act as slaves,
copying and rebroadcasting the LED states of other nodes.

==== BLE Gateway example
This example uses the same configuration for LEDs as the LED Mesh example, but
provides a S110 Softdevice profile for communication with external nodes in
stead of a physical interface. The example application starts sending
regular connectable BLE advertisements with the Softdevice, and displays the
Mesh service in its GATT server, so that external nodes may write to the two
LED config values as if they were regular characteristics. 

== How it works
=== GATT Service
=== Trickle Algorithm
=== Timeslots
=== Resource allocation

== Forum
http://devzone.nordicsemi.com/[Nordic Developer Zone]

== Resources
http://www.nordicsemi.com[Nordic Semiconductor Homepage] 

http://tools.ietf.org/html/rfc6206[Trickle Algorithm Specification]


