= Scaling example
\- A display of how to handle a lot of instances

This example uses UART to control mesh nodes with a significant number of data 
instances. The devices can be interfaced via a regular serial communication
application on your PC, using some simple commands to set values and disable 
propagation.

By default, all devices store 100 handle-value pairs, but this number can be 
configured in the main.c file.

Note that this example does not mirror the entire API, and is not meant to 
replace the existing SPI ACI interface.

== Usage:
Set up any number of devices and connect two or more to a serial terminal 
session on your computer with the parameters specified below. Use the commands 
below to set values, and read them back as events from another device.

== Changing the number of instances:
The number of instances on each device can be configured by setting the 
`HANDLE_COUNT` #define in _main.c_. Note that if you try to allocate more than 
100 handle-value pairs, you might need to increase the memory area allocated 
for the Softdevice. This can be done by changing the application RAM starting 
point in the "Target options"->"Target" in Keil uVision, or in the linker file
in the gcc directory. In addition, the predefined 
RBC_MESH_GATTS_ATTR_TABLE_SIZE needs to be set accordingly, as defined in the 
Softdevice specification document. For gcc, this variable can be set at the 
top of the makefile.

Also note that the HEAP size has been set to 4096 in the startup file, which 
should be sufficient to store any number of handles.

== RTT-logging
As a faster alternative to UART, the SEGGER Real Time Transfer functionality
may be utilized. Simply set the LOG_RTT flag in the beginning of main.c, and
start a host side RTT session on your computer as specified on the Segger
website, https://www.segger.com/rtt.html.

== UART interface syntax:
=== Commands:
Set value: "U <handle number> <content>"
Disable trickle: "D <handle number>"

End with enter (\\r or \\n).

=== Events:
RBC_MESH event: "<evt type>[<handle number>] <content>"
<evt_type>:
U = update
C = conflict
N = new
I = init framework (will not occur without SPI)

Events ends with a CRLF.

== UART settings:

Baud: 460800

Data bits: 8

Parity bit: no

Stop bit: 1

Flow control enabled (RTS/CTS)
