#ifndef _RADIO_CONTROL_H__
#define _RADIO_CONTROL_H__
#include <stdint.h>

/** @brief callbacks for after radio event is complete */
typedef void (*radio_rx_cb)(uint8_t*);
typedef void (*radio_tx_cb)(void);

typedef enum
{
    RADIO_EVENT_TYPE_TX,
    RADIO_EVENT_TYPE_RX
} radio_event_type_t;

/**
* @brief executable radio event type 
*/
typedef struct
{
    radio_event_type_t event_type;  /* RX/TX */
    uint32_t start_time;            /* time to start the event. 0 indicates as soon as possible */
    uint8_t* packet_ptr;            /* packet pointer to use. TX ONLY */
    uint8_t access_address;         /* If TX: access address index to send on. If RX: AA enabled bitfield */
    uint8_t channel;                /* Channel to execute event on */
    union 
    {
        radio_rx_cb rx;
        radio_tx_cb tx;
    } callback;
} radio_event_t;

/**
* @brief Starts the radio init procedure
*   Must be called at the beginning of each timeslot
*
* @param[in] access_addr access address to put in aa slot 0
*/
void radio_init(uint32_t access_address);

/**
* @brief Schedule a radio event (tx/rx)
* 
* @param[in] radio_event pointer to user-created radio event to be queued. 
*   Is copied into queue, may be stack allocated
*/
void radio_order(radio_event_t* radio_event);

/**
* @brief Disable the radio. Overrides any ongoing rx or tx procedures
*/
void radio_disable(void);


/**
* @brief Radio event handler, checks any relevant events generated by the radio, and acts accordingly
*/
void radio_event_handler(void);



#endif /* _RADIO_CONTROL_H__*/
